server:
  port: 9002
  servlet:
    context-path: /power-bank
spring:
  application:
    name: power-bank
  redis:
        database: 1
        password: 1234
        port: 6379
        host: 127.0.0.1
        timeout: 5000
  datasource:
      url: jdbc:mysql://localhost:3306/hgl_tech?useUnicode=true&characterEncoding=UTF-8
      username: root
      password: 1234
      driver-class-name: com.mysql.jdbc.Driver


mybatis:
  mapper-locations: classpath:mapper/*.xml


